// <auto-generated />
using System;
using HRPlatform.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HRPlatform.Migrations
{
    [DbContext(typeof(DataBase))]
    [Migration("20220412174422_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("HRPlatform.Models.Candidate", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Candidate");
                });

            modelBuilder.Entity("HRPlatform.Models.Skill", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateName")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.HasIndex("CandidateName");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("HRPlatform.Models.Skill", b =>
                {
                    b.HasOne("HRPlatform.Models.Candidate", null)
                        .WithMany("Skills")
                        .HasForeignKey("CandidateName");
                });

            modelBuilder.Entity("HRPlatform.Models.Candidate", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
